# NLP Execise from Day 1 to 100 -> Zero to Hero

> Basics of Tokenization

In [15]:
import spacy

nlp = spacy.load('en_core_web_sm')
text = "Hi, I am looking for a job! Can you please provide me details"

res = nlp(text)
for sentences in res.sents:
    print(sentences)

Hi, I am looking for a job!
Can you please provide me details

In [16]:
for sentences in res:
    print(sentences)

Hi
,
I
am
looking
for
a
job
!
Can
you
please
provide
me
details

In [17]:
import nltk

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/alhaanahmed/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [18]:
from nltk.text import sent_tokenize

docs = sent_tokenize(text)
print(docs)

['Hi, I am looking for a job!', 'Can you please provide me details']

In [19]:
from nltk.tokenize import word_tokenize

docs = word_tokenize(text)

print(docs)

['Hi', ',', 'I', 'am', 'looking', 'for', 'a', 'job', '!', 'Can', 'you', 'please', 'provide', 'me', 'details']

> Understanding the concept of Language Processing Pipeline.

SpaCy provide us pretrained models such as en_core_web_sm for english language that allows us to create a pipeline and add components such as POS (Parts of Speech Tagging), Lemmatization, NER (Named Entity Recognition) etc

In [20]:
# Using the preloaded pipeline and outputting characterisitics
nlp = spacy.load("en_core_web_sm")
text = nlp("Imran Khan was the leading Captain of ICC World Cup 1992 and He led Pakistan to a victory against England")

for doc in text:
    print(doc, " | ", doc.pos_, " | ", doc.lemma_)

Imran  |  PROPN  |  Imran
Khan  |  PROPN  |  Khan
was  |  AUX  |  be
the  |  DET  |  the
leading  |  VERB  |  lead
Captain  |  PROPN  |  Captain
of  |  ADP  |  of
ICC  |  PROPN  |  ICC
World  |  PROPN  |  World
Cup  |  PROPN  |  Cup
1992  |  NUM  |  1992
and  |  CCONJ  |  and
He  |  PRON  |  he
led  |  VERB  |  lead
Pakistan  |  PROPN  |  Pakistan
to  |  ADP  |  to
a  |  DET  |  a
victory  |  NOUN  |  victory
against  |  ADP  |  against
England  |  PROPN  |  England

In [21]:
# Finding NER entities in text with explaination
for token in text.ents:
    print(token.text, " | ", token.label_, " | ", spacy.explain(token.label_))

Khan  |  PERSON  |  People, including fictional
Captain of ICC World Cup 1992  |  ORG  |  Companies, agencies, institutions, etc.
Pakistan  |  GPE  |  Countries, cities, states
England  |  GPE  |  Countries, cities, states

In [22]:
from spacy import displacy

displacy.render(text, style="ent")

## Stemming and Lemmatization

> **Stemming** is a technique in which words are stemmed into base words, I mean simple words are converted into Base words for example eating to eat, adaptive to adapt.

> Whereas **Lemmatization** is an improved version of stemming which not only looks for suffixes or prefixes but has knowledge of that particular language for example, ate to eat.

Using NLTK we can do both stemming and lemmatization

In [23]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

words = ["adaptive", "talkative", "processing", "added", "sealed", "forged", "shooting", "drafting"]

for word in words:
    print("Word: " + word, "| Stemmed Word: " +  stemmer.stem(word))

Word: adaptive | Stemmed Word: adapt
Word: talkative | Stemmed Word: talk
Word: processing | Stemmed Word: process
Word: added | Stemmed Word: ad
Word: sealed | Stemmed Word: seal
Word: forged | Stemmed Word: forg
Word: shooting | Stemmed Word: shoot
Word: drafting | Stemmed Word: draft

In [24]:
docs = nlp("Hey yo, are you in this list. I think i might have messed with ya.!")

for doc in docs:
    print(doc, doc.lemma_)

Hey hey
yo yo
, ,
are be
you you
in in
this this
list list
. .
I I
think think
i I
might might
have have
messed mess
with with
ya ya
. .
! !

In [25]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [26]:
attr = nlp.get_pipe("attribute_ruler")

attr.add([[{"TEXT": "yo"}], [{"TEXT": "ya"}]], {"LEMMA": "you"})
docs = nlp("Hey yo, you in. I think ya messed with me.!")
for doc in docs:
    print(doc, doc.lemma_)

Hey hey
yo you
, ,
you you
in in
. .
I I
think think
ya you
messed mess
with with
me I
. .
! !

> POS Tagging

In [27]:
text = """Ali Hosseini Khamenei (19 April 1939 – 28 February 2026) 
was an Iranian politician and Shia cleric who served as 
the second supreme leader of Iran from 1989 until his assassination at the onset of 
the 2026 Iran war. He previously served as the third president of Iran from 1981 to 1989. 
His tenure as supreme leader, spanning 36 years and six months, 
made him the longest-serving head of state in West Asia at the time of his death.
He held the title of Ayatollah and was considered one of the world's leading maraji' of Twelver Shi'ism.
Born into the Khamenei family, 
he studied at a hawza in his hometown of Mashhad, 
later settling in Qom in 1958, where he attended the classes of Ruhollah Khomeini. 
Khamenei became involved in opposition to the Shah Mohammad Reza Pahlavi, 
and was arrested six times before being exiled for three years by the Shah's regime.
Khamenei was a mainstream figure in the Iranian Revolution, and upon its success,
held many posts in the newly established Islamic republic. 
In the aftermath of the revolution, he was the target of an attempted assassination 
that paralysed his right arm. There had been continued assassination threats 
against Khamenei by Israel. Khamenei served as the third president of Iran from 1981 to 1989 
during the Iran–Iraq War, when he also developed close ties to the 
Islamic Revolutionary Guard Corps (IRGC). After the death and state funeral of 
Ruhollah Khomeini in 1989, Khamenei was elected supreme leader by the Assembly of Experts. During the deliberations, Khamenei expressed reservations about his religious qualifications and suitability for the position. As opposed to his predecessor, who held the rank of Grand Ayatollah, Khamenei was then a mid-ranking cleric and did not meet the constitutional requirement of marja'. The constitution was subsequently amended to remove that requirement, and the Assembly reconfirmed his leadership later that year."""

In [28]:
docs = nlp(text)

all_nouns = []
all_verbs = []
for doc in docs:
    if doc.pos_ == "NOUN" or doc.pos_ == "PROPN":
        all_nouns.append(doc.text)
    elif doc.pos_ == "VERB":
        all_verbs.append(doc.text)
        

all_nouns[:20]

['Ali',
 'Hosseini',
 'Khamenei',
 'April',
 'February',
 'politician',
 'Shia',
 'cleric',
 'leader',
 'Iran',
 'assassination',
 'onset',
 'Iran',
 'war',
 'president',
 'Iran',
 'tenure',
 'supreme',
 'leader',
 'years']

In [29]:
all_verbs[:20]

['served',
 'served',
 'spanning',
 'made',
 'serving',
 'held',
 'considered',
 'leading',
 'Born',
 'studied',
 'settling',
 'attended',
 'became',
 'arrested',
 'exiled',
 'held',
 'established',
 'attempted',
 'paralysed',
 'continued']

# Build a Spam and Ham SMS Classifier using Bag of Words and CountVectorizer

In [36]:
import pandas as pd
df = pd.read_csv("spam.csv")

In [37]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [38]:
df.iloc[0]

v1                                                          ham
v2            Go until jurong point, crazy.. Available only ...
Unnamed: 2                                                  NaN
Unnamed: 3                                                  NaN
Unnamed: 4                                                  NaN
Name: 0, dtype: str

In [45]:
df.dropna(axis=1, inplace=True)

In [46]:
df.rename(columns={"v1": "Class", "v2": "Message"})

     Class                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]